# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Test, audit and lint"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: advent_test
          POSTGRES_USER: advent
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV       : test
      DB_HOST         : localhost
      DB_PORT         : 5432
      DB_USER         : advent
      DB_PASS         : password
      SECRET_KEY_BASE : 48fef7bcfd20d260074b29a17eb50f5eb3c1c1903100c747e43a7e1b457575b6d06dd0f9e0ee1391af0cb5ebbbb48c69c4565e97a5f7a85d216c5851a5286eda

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: bin/bundle exec rspec

  brakeman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Security audit application code
        run: bin/bundle exec brakeman -q -w2

  # rubocop:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
  #       with:
  #         bundler-cache: true
  #     - name: Lint Ruby files
  #       run: bin/rubocop --parallel
